=begin
Dog Hero

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration[4.2]
  def change
    create_table "host".pluralize.to_sym, id: false do |t|
      t.boolean :availability_confirmed
      t.string :chopped_desc
      t.string :highlights
      t.boolean :favorite
      t.float :id
      t.boolean :is_superhero
      t.string :last_review
      t.string :locale
      t.float :rating
      t.string :region_address
      t.float :reviews_count
      t.string :title
      t.string :user

      t.timestamps
    end

    create_table "host_highlights".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :value

      t.timestamps
    end

    create_table "host_last_review".pluralize.to_sym, id: false do |t|
      t.string :body
      t.string :client_image_url
      t.string :client_name

      t.timestamps
    end

    create_table "host_locale".pluralize.to_sym, id: false do |t|
      t.string :country
      t.float :price
      t.string :currency

      t.timestamps
    end

    create_table "host_user".pluralize.to_sym, id: false do |t|
      t.string :first_name
      t.string :image_url

      t.timestamps
    end

  end
end
